"""Export public presentation assets; never query or serialize household data."""

import json
import re
from pathlib import Path

from django import forms as django_forms
from django.conf import settings
from django.core.management.base import BaseCommand, CommandError
from django.template import Context
from django.template.loader import get_template
from django.template.loader_tags import BlockNode

from directory import forms
from directory.templatetags.portal_tags import ICONS


FORM_CLASSES = {
    "signup": forms.ParentRegistrationForm,
    "login": forms.ParentAuthenticationForm,
    "join": forms.GuardianJoinForm,
    "child": forms.ChildForm,
    "phone": forms.PhoneReservationForm,
    "quiet": forms.ChildBlackoutPeriodForm,
    "family": forms.FamilySettingsForm,
    "profile": forms.GuardianProfileForm,
    "contact": forms.FamilyContactForm,
    "shortcut": forms.ShortcutForm,
    "invitation": forms.ConnectionInvitationForm,
    "accept": forms.ConnectionAcceptForm,
    "guardian": forms.GuardianInvitationForm,
    "code": forms.InviteCodeForm,
    "group": forms.ConferenceGroupForm,
}


def field_definition(name, field):
    widget = field.widget
    dynamic = isinstance(field, django_forms.ModelMultipleChoiceField)
    kind = "text"
    if dynamic:
        kind = "members"
    elif isinstance(widget, django_forms.Textarea):
        kind = "textarea"
    elif isinstance(widget, django_forms.Select):
        kind = "select"
    else:
        kind = widget.attrs.get("type", getattr(widget, "input_type", "text"))
    definition = {
        "name": name,
        "label": str(field.label or name.replace("_", " ").capitalize()),
        "required": field.required,
        "type": kind,
        "help": str(field.help_text),
    }
    for attribute in ("max_length", "min_length"):
        value = getattr(field, attribute, None)
        if value is not None:
            definition[attribute] = value
    if isinstance(field.initial, (str, bool, int)):
        definition["initial"] = field.initial
    if isinstance(field, django_forms.ChoiceField) and not dynamic:
        definition["choices"] = [[str(k), str(v)] for k, v in field.choices]
    return definition


def exported_assets():
    root = Path(settings.BASE_DIR)
    static = root / "directory/static/directory"
    # Compile the real public welcome block, including its real icon tags.
    template = get_template("directory/welcome.html").template
    content = next(
        node
        for node in template.nodelist.get_nodes_by_type(BlockNode)
        if node.name == "content"
    )
    # The public demo deliberately includes fictional onboarding, regardless of
    # whether a private deployment has registration enabled.
    context = Context({"portal_allow_registration": True})
    with context.bind_template(template):
        welcome = content.render(context)
    # Template conditionals may add indentation without changing the page.
    # Keep one newline between tags so inline whitespace stays meaningful.
    welcome = re.sub(r">\s*\n\s*<", ">\n<", welcome).strip()
    contract = {
        "icons": ICONS,
        "forms": {
            name: [
                field_definition(key, field)
                for key, field in (
                    cls().fields if name == "login" else cls.base_fields
                ).items()
                if not field.widget.is_hidden
            ]
            for name, cls in FORM_CLASSES.items()
        },
        "welcome": welcome,
    }
    assets = {
        "portal-contract.js": (
            "// Generated by manage.py export_browser_demo. Do not edit.\n"
            "const PORTAL = "
            + json.dumps(contract, ensure_ascii=False, indent=2)
            + ";\n"
        ).encode(),
        "styles.css": static.joinpath("portal.css").read_bytes(),
        "favicon.svg": static.joinpath("favicon.svg").read_bytes(),
    }
    for path in sorted(static.joinpath("fonts").iterdir()):
        if path.is_file():
            assets[f"fonts/{path.name}"] = path.read_bytes()
    return assets


class Command(BaseCommand):
    help = "Sync the standalone demo's public styles, fonts, icons, forms and welcome."
    requires_system_checks = []

    def add_arguments(self, parser):
        parser.add_argument(
            "--check", action="store_true", help="Fail on stale exports."
        )

    def handle(self, *args, **options):
        destination = Path(settings.BASE_DIR) / "ui-prototype/dist"
        stale = []
        for name, content in exported_assets().items():
            path = destination / name
            if path.exists() and path.read_bytes() == content:
                continue
            stale.append(name)
            if not options["check"]:
                path.parent.mkdir(parents=True, exist_ok=True)
                path.write_bytes(content)
        if options["check"] and stale:
            raise CommandError(
                "Browser demo assets are stale: "
                + ", ".join(stale)
                + ". Run python manage.py export_browser_demo and commit the exports."
            )
        self.stdout.write(
            "Browser demo assets are current."
            if not stale
            else f"Updated {len(stale)} browser demo assets."
        )
