FROM python:3.12-slim-bookworm

ENV PYTHONDONTWRITEBYTECODE=1 \
    PYTHONUNBUFFERED=1 \
    UV_PROJECT_ENVIRONMENT=/usr/local

WORKDIR /app

# Pinned local TTS and μ-law conversion tools keep private prompts offline and
# make their generated bytes reproducible across FrontPorch image rebuilds.
RUN apt-get update && \
    apt-get install --yes --no-install-recommends \
        espeak-ng=1.51+dfsg-10+deb12u2 \
        libsox-fmt-base=14.4.2+git20190427-3.5 \
        sox=14.4.2+git20190427-3.5 && \
    rm -rf /var/lib/apt/lists/*

RUN pip install --no-cache-dir uv

COPY pyproject.toml uv.lock ./
RUN uv sync --frozen --no-dev

COPY . .

EXPOSE 8000

CMD ["gunicorn", "frontporch.wsgi:application", "--bind", "0.0.0.0:8000"]
