import os
from pathlib import Path
from tempfile import NamedTemporaryFile

from directory.asterisk.tts import (
    MENU_EXTENSION_TEXT,
    menu_shortcut_text,
    spoken_prompt,
    text_to_speech_settings,
)


GENERATED_HEADER = "; GENERATED BY FRONTPORCH\n; DO NOT EDIT BY HAND\n"
PJSIP_FILENAME = "pjsip_frontporch.conf"
EXTENSIONS_FILENAME = "extensions_frontporch.conf"


class AsteriskConfigRenderer:
    def render_pjsip(self, configuration):
        lines = [GENERATED_HEADER.rstrip(), ""]

        for endpoint in configuration.endpoints:
            lines.extend(
                [
                    f"[{endpoint.endpoint_name}](endpoint-basic)",
                    f"context={endpoint.context_name}",
                    f"auth={endpoint.auth_name}",
                    f"aors={endpoint.aor_name}",
                    f'callerid="{endpoint.owner_display_name}" <{endpoint.extension}>',
                    "",
                    f"[{endpoint.auth_name}](auth-userpass)",
                    f"username={endpoint.username}",
                    f"password={endpoint.secret}",
                    "",
                    f"[{endpoint.aor_name}](aor-single-reg)",
                    "",
                ]
            )

        return "\n".join(lines).rstrip() + "\n"

    def render_extensions(self, configuration):
        rules_by_context = {}
        for rule in configuration.dialplan_rules:
            rules_by_context.setdefault(rule.source_endpoint.context_name, []).append(rule)
        external_rules_by_context = {}
        for rule in configuration.external_dialplan_rules:
            external_rules_by_context.setdefault(
                rule.source_endpoint.context_name,
                [],
            ).append(rule)
        shortcut_rules_by_context = {}
        for rule in configuration.shortcut_rules:
            shortcut_rules_by_context.setdefault(
                rule.source_endpoint.context_name,
                [],
            ).append(rule)

        lines = [GENERATED_HEADER.rstrip(), ""]

        for endpoint in configuration.endpoints:
            lines.append(f"[{endpoint.context_name}]")
            lines.append("include => frontporch-diagnostics")
            lines.append("")
            lines.extend(
                [
                    "exten => 100,1,Goto(frontporch-diagnostics,100,1)",
                    "",
                ]
            )
            shortcut_groups = _group_rules_by_value(
                shortcut_rules_by_context.get(endpoint.context_name, []),
                lambda rule: rule.digits,
            )
            for shortcut_rules in shortcut_groups.values():
                lines.extend(
                    self._render_shortcut_rules(
                        shortcut_rules,
                        outbound_caller_id=configuration.outbound_caller_id,
                    )
                )
            target_groups = _group_rules_by_value(
                rules_by_context.get(endpoint.context_name, []),
                lambda rule: rule.dialed_extension,
            )
            for dialed_extension, target_rules in target_groups.items():
                targets = _unique_targets(target_rules)
                target = targets[0]
                lines.extend(
                    self._render_call_lines(
                        f"exten => {dialed_extension},1,",
                        source_endpoint=target_rules[0].source_endpoint,
                        target_endpoints=targets,
                        outbound_caller_id=self._outbound_caller_id_for_target(
                            target,
                            configuration.outbound_caller_id,
                        ),
                    )
                )
            for rule in external_rules_by_context.get(endpoint.context_name, []):
                lines.extend(
                    self._render_call_lines(
                        f"exten => {rule.dialed_extension},1,",
                        source_endpoint=rule.source_endpoint,
                        dial_target=f"PJSIP/{rule.outbound_number}@voipms-endpoint",
                        outbound_caller_id=configuration.outbound_caller_id,
                    )
                )
            lines.extend(
                [
                    "exten => _X!,1,Hangup(21)",
                    "",
                ]
            )

        lines.extend(self._render_blackout_context())
        lines.extend(self._render_public_inbound_context(configuration))

        return "\n".join(lines).rstrip() + "\n"

    def _render_shortcut_rules(self, rules, outbound_caller_id=""):
        rule = rules[0]
        if rule.is_external:
            dial_target = f"PJSIP/{rule.outbound_number}@voipms-endpoint"
            target_endpoint = None
            target_endpoints = ()
            caller_id = outbound_caller_id
        else:
            target_endpoints = _unique_targets(rules)
            target_endpoint = target_endpoints[0]
            dial_target = None
            caller_id = self._outbound_caller_id_for_target(
                target_endpoint,
                outbound_caller_id,
            )
        return self._render_call_lines(
            f"exten => {rule.digits},1,",
            source_endpoint=rule.source_endpoint,
            target_endpoint=target_endpoint,
            target_endpoints=target_endpoints,
            dial_target=dial_target,
            outbound_caller_id=caller_id,
        )

    def _render_call_lines(
        self,
        first_prefix,
        source_endpoint=None,
        target_endpoint=None,
        target_endpoints=(),
        dial_target=None,
        outbound_caller_id="",
        generate_ringback=False,
    ):
        if target_endpoints:
            target_endpoint = target_endpoints[0]
        if dial_target is None:
            dial_target = (
                "&".join(endpoint.dial_target for endpoint in target_endpoints)
                if target_endpoints
                else target_endpoint.dial_target
            )

        blackout_checks = self._call_blackout_checks(source_endpoint, target_endpoint)
        outbound_setup = []
        if outbound_caller_id:
            outbound_setup.append(f"Set(CALLERID(num)={outbound_caller_id})")

        dial_options = ",r" if generate_ringback else ""
        applications = blackout_checks + outbound_setup + [
            f"Dial({dial_target},30{dial_options})",
            "Hangup()",
        ]
        return (
            [f"{first_prefix}{applications[0]}"]
            + [f" same => n,{application}" for application in applications[1:]]
            + [""]
        )

    def _outbound_caller_id_for_target(self, target_endpoint, outbound_caller_id):
        if outbound_caller_id and hasattr(target_endpoint, "child_landline_id"):
            return outbound_caller_id
        return ""

    def _call_blackout_checks(self, source_endpoint=None, target_endpoint=None):
        windows = []
        endpoint_pairs = (
            (source_endpoint, target_endpoint),
            (target_endpoint, source_endpoint),
        )
        for endpoint, other_endpoint in endpoint_pairs:
            if endpoint is None:
                continue
            if self._blackout_exception_applies(endpoint, other_endpoint):
                continue
            windows.extend(endpoint.blackout_windows)
        return [
            (
                f"GotoIfTime({window.time_range},{window.days},*,*?"
                "frontporch-blackout,s,1)"
            )
            for window in windows
        ]

    def _blackout_exception_applies(self, endpoint, other_endpoint):
        if not endpoint.blackout_windows or other_endpoint is None:
            return False
        return (
            endpoint.owner_type == "child"
            and endpoint.family_id == other_endpoint.family_id
            and other_endpoint.owner_type in {"parent", "family"}
        )

    def _render_blackout_context(self):
        return [
            "[frontporch-blackout]",
            "exten => s,1,NoOp(Rejecting call during child blackout period)",
            " same => n,Hangup(21)",
            "",
        ]

    def _render_public_inbound_context(self, configuration):
        inbound_context_name = "frontporch-public-inbound"
        if configuration.public_inbound_numbers:
            inbound_context_name = configuration.public_inbound_numbers[
                0
            ].inbound_context_name

        inbound_rules_by_public_number_id = {}
        for rule in configuration.inbound_external_caller_rules:
            inbound_rules_by_public_number_id.setdefault(
                rule.public_phone_number_id,
                [],
            ).append(rule)
        landline_rules_by_public_number_id = {}
        for rule in configuration.inbound_landline_caller_rules:
            landline_rules_by_public_number_id.setdefault(
                rule.public_phone_number_id,
                [],
            ).append(rule)
        landline_shortcuts_by_public_number_id = {}
        for rule in configuration.inbound_landline_shortcut_rules:
            landline_shortcuts_by_public_number_id.setdefault(
                rule.public_phone_number_id,
                [],
            ).append(rule)

        lines = [f"[{inbound_context_name}]"]
        restricted_contexts = []

        for public_number in configuration.public_inbound_numbers:
            canonical = public_number.canonical_extension
            caller_groups = {}
            for rule in inbound_rules_by_public_number_id.get(
                public_number.public_phone_number_id,
                (),
            ):
                caller_groups.setdefault(rule.caller_normalized_number, []).append(rule)
            landline_caller_groups = {}
            for rule in landline_rules_by_public_number_id.get(
                public_number.public_phone_number_id,
                (),
            ):
                landline_caller_groups.setdefault(
                    rule.caller_normalized_number,
                    [],
                ).append(rule)
            landline_shortcut_groups = {}
            for rule in landline_shortcuts_by_public_number_id.get(
                public_number.public_phone_number_id,
                (),
            ):
                landline_shortcut_groups.setdefault(
                    rule.caller_normalized_number,
                    [],
                ).append(rule)

            lines.extend(
                [
                    (
                        f"exten => {canonical},1,"
                        f"NoOp(FrontPorch public inbound for {public_number.normalized_number})"
                    ),
                ]
            )
            approved_branches = []
            for rule_index, (caller_number, caller_rules) in enumerate(
                sorted(landline_caller_groups.items()),
                start=1,
            ):
                caller_rules = sorted(
                    caller_rules,
                    key=lambda rule: (
                        rule.target_endpoint.extension,
                        _endpoint_sort_identity(rule.target_endpoint),
                    ),
                )
                target_groups = _group_rules_by_value(
                    caller_rules,
                    lambda rule: rule.target_endpoint.extension,
                )
                if len(target_groups) == 1:
                    label = f"approved-landline-{canonical}-{rule_index}"
                    destination = label
                    targets = _unique_targets(next(iter(target_groups.values())))
                    approved_branches.extend(
                        self._render_labeled_target_call(
                            label,
                            targets,
                            configuration.outbound_caller_id,
                            generate_ringback=True,
                        )
                    )
                else:
                    context_name = (
                        f"frontporch-landline-inbound-"
                        f"{public_number.public_phone_number_id}-{rule_index}"
                    )
                    destination = f"{context_name},s,1"
                    restricted_contexts.append(
                        (
                            context_name,
                            caller_number,
                            caller_rules,
                            landline_shortcut_groups.get(caller_number, ()),
                            True,
                        )
                    )

                for caller_id in caller_rules[0].caller_id_variants:
                    lines.append(
                        (
                            ' same => n,GotoIf($["${CALLERID(num)}" = '
                            f'"{caller_id}"]?{destination})'
                        )
                    )

            for rule_index, (caller_number, caller_rules) in enumerate(
                sorted(caller_groups.items()),
                start=1,
            ):
                caller_rules = sorted(
                    caller_rules,
                    key=lambda rule: (
                        rule.target_endpoint.extension,
                        _endpoint_sort_identity(rule.target_endpoint),
                    ),
                )
                target_groups = _group_rules_by_value(
                    caller_rules,
                    lambda rule: rule.target_endpoint.extension,
                )
                if len(target_groups) == 1:
                    label = f"approved-{canonical}-{rule_index}"
                    destination = label
                    targets = _unique_targets(next(iter(target_groups.values())))
                    approved_branches.extend(
                        self._render_labeled_target_call(
                            label,
                            targets,
                            configuration.outbound_caller_id,
                        )
                    )
                else:
                    context_name = (
                        f"frontporch-inbound-{public_number.public_phone_number_id}"
                        f"-{rule_index}"
                    )
                    destination = f"{context_name},s,1"
                    restricted_contexts.append(
                        (context_name, caller_number, caller_rules, (), False)
                    )

                for caller_id in caller_rules[0].caller_id_variants:
                    lines.append(
                        (
                            ' same => n,GotoIf($["${CALLERID(num)}" = '
                            f'"{caller_id}"]?{destination})'
                        )
                    )
            lines.extend(
                [
                    (
                        " same => n,NoOp(Rejecting unapproved public inbound caller "
                        "${CALLERID(num)})"
                    ),
                    " same => n,Hangup(21)",
                    "",
                ]
            )
            lines.extend(approved_branches)
            if approved_branches:
                lines.append("")

            for extension in public_number.dialplan_extensions:
                if extension == canonical:
                    continue
                lines.extend(
                    [
                        (
                            f"exten => {extension},1,"
                            f"Goto({inbound_context_name},{canonical},1)"
                        ),
                        "",
                    ]
                )

        lines.extend(
            [
                "exten => _X!,1,NoOp(Rejecting unmatched public inbound destination ${EXTEN})",
                " same => n,Hangup(21)",
                "",
            ]
        )

        for (
            context_name,
            caller_number,
            caller_rules,
            shortcut_rules,
            is_spoken_landline_menu,
        ) in restricted_contexts:
            target_groups = _group_rules_by_value(
                caller_rules,
                lambda rule: rule.target_endpoint.extension,
            )
            shortcut_groups = _group_rules_by_value(
                shortcut_rules,
                lambda rule: rule.digits,
            )
            lines.extend(
                [
                    f"[{context_name}]",
                    (
                        f"exten => s,1,NoOp(FrontPorch restricted inbound caller "
                        f"{caller_number})"
                    ),
                    " same => n,Answer()",
                ]
            )
            if is_spoken_landline_menu:
                lines.extend(
                    [
                        " same => n,Set(FRONTPORCH_MENU_ATTEMPT=1)",
                    ]
                )
                lines.extend(
                    self._landline_menu_background_lines(
                        configuration,
                        shortcut_groups,
                    )
                )
                lines.extend([" same => n,WaitExten(10)", ""])
            else:
                lines.extend(
                    [
                        " same => n,WaitExten(10)",
                        " same => n,Hangup(21)",
                        "",
                    ]
            )
            for digits, digit_rules in shortcut_groups.items():
                targets = _unique_targets(digit_rules)
                lines.extend(
                    self._render_call_lines(
                        f"exten => {digits},1,",
                        target_endpoints=targets,
                        outbound_caller_id=self._outbound_caller_id_for_target(
                            targets[0],
                            configuration.outbound_caller_id,
                        ),
                        generate_ringback=is_spoken_landline_menu,
                    )
                )
            for extension, target_rules in target_groups.items():
                targets = _unique_targets(target_rules)
                lines.extend(
                    self._render_call_lines(
                        f"exten => {extension},1,",
                        target_endpoints=targets,
                        outbound_caller_id=self._outbound_caller_id_for_target(
                            targets[0],
                            configuration.outbound_caller_id,
                        ),
                        generate_ringback=is_spoken_landline_menu,
                    )
                )
            if is_spoken_landline_menu:
                lines.extend(self._render_spoken_menu_retry_rules())
            else:
                lines.extend(
                    [
                        "exten => i,1,Hangup(21)",
                        "exten => t,1,Hangup(21)",
                        "exten => _X!,1,Hangup(21)",
                        "",
                    ]
                )

        return lines

    def _landline_menu_background_lines(self, configuration, shortcut_groups):
        prompt_settings = (
            configuration.text_to_speech_settings or text_to_speech_settings()
        )
        lines = []
        is_first_prompt = True
        for digits, rules in shortcut_groups.items():
            rule = rules[0]
            child_name = (
                rule.target_child_name or rule.target_endpoint.owner_display_name
            )
            sounds = spoken_prompt(
                menu_shortcut_text(digits, child_name),
                prompt_settings,
            ).sound_name
            label = "(menu)" if is_first_prompt else ""
            lines.append(f" same => n{label},Background({sounds})")
            is_first_prompt = False
        extension_prompt = spoken_prompt(
            MENU_EXTENSION_TEXT,
            prompt_settings,
        ).sound_name
        label = "(menu)" if is_first_prompt else ""
        lines.append(f" same => n{label},Background({extension_prompt})")
        return lines

    def _render_spoken_menu_retry_rules(self):
        return [
            (
                'exten => i,1,GotoIf($["${FRONTPORCH_MENU_ATTEMPT}" = "1"]?'
                "retry,1:goodbye,1)"
            ),
            (
                'exten => t,1,GotoIf($["${FRONTPORCH_MENU_ATTEMPT}" = "1"]?'
                "retry,1:goodbye,1)"
            ),
            "exten => retry,1,Set(FRONTPORCH_MENU_ATTEMPT=2)",
            " same => n,Playback(please-try-again)",
            " same => n,Goto(s,menu)",
            "exten => goodbye,1,Playback(goodbye)",
            " same => n,Hangup(21)",
            "",
        ]

    def _render_labeled_target_call(
        self,
        label,
        target_endpoints,
        outbound_caller_id="",
        generate_ringback=False,
    ):
        return self._render_call_lines(
            f" same => n({label}),",
            target_endpoints=target_endpoints,
            outbound_caller_id=self._outbound_caller_id_for_target(
                target_endpoints[0],
                outbound_caller_id,
            ),
            generate_ringback=generate_ringback,
        )

    def render_files(self, configuration):
        return {
            PJSIP_FILENAME: self.render_pjsip(configuration),
            EXTENSIONS_FILENAME: self.render_extensions(configuration),
        }

    def write_files(self, configuration, output_dir):
        output_path = Path(output_dir)
        output_path.mkdir(parents=True, exist_ok=True)

        written = []
        for filename, content in self.render_files(configuration).items():
            destination = output_path / filename
            _atomic_write(destination, content)
            written.append(destination)
        return tuple(written)


def _atomic_write(destination, content):
    destination = Path(destination)
    with NamedTemporaryFile(
        "w",
        encoding="utf-8",
        dir=destination.parent,
        delete=False,
    ) as temporary:
        temporary.write(content)
        temporary_path = Path(temporary.name)

    os.chmod(temporary_path, 0o644)
    os.replace(temporary_path, destination)


def _endpoint_sort_identity(endpoint):
    if hasattr(endpoint, "device_id"):
        return ("sip", endpoint.device_id)
    return ("landline", endpoint.child_landline_id)


def _group_rules_by_value(rules, value):
    groups = {}
    for rule in rules:
        groups.setdefault(value(rule), []).append(rule)
    return groups


def _unique_targets(rules):
    targets_by_identity = {}
    for rule in rules:
        target = rule.target_endpoint
        targets_by_identity.setdefault(_endpoint_sort_identity(target), target)
    return tuple(targets_by_identity.values())
