# Generated by Django 5.2.15 on 2026-08-09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("directory", "0010_family_contact_extensions"),
    ]

    operations = [
        migrations.AlterField(
            model_name="device",
            name="sip_extension",
            field=models.CharField(
                db_index=True,
                help_text=(
                    "Devices assigned to the same owner may share an extension while "
                    "using separate SIP credentials."
                ),
                max_length=32,
            ),
        ),
    ]
