# Generated by Django 5.2.15 on 2026-08-20 22:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0011_device_shared_extension'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChildLandlineDialShortcut',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('digits', models.CharField(max_length=1)),
                ('label', models.CharField(blank=True, max_length=200)),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
                ('approved_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='approved_child_landline_dial_shortcuts', to='directory.parent')),
                ('source_landline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dial_shortcuts', to='directory.childlandline')),
                ('target_child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='targeted_by_landline_shortcuts', to='directory.child')),
            ],
            options={
                'ordering': ['source_landline__child__family__name', 'source_landline__child__name', 'digits'],
                'constraints': [models.UniqueConstraint(fields=('source_landline', 'digits'), name='unique_digits_per_child_landline'), models.UniqueConstraint(fields=('source_landline', 'target_child'), name='unique_target_per_child_landline')],
            },
        ),
    ]
