# Generated by Django 5.2.15 on 2026-08-20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("directory", "0012_childlandlinedialshortcut"),
    ]

    operations = [
        migrations.AddField(
            model_name="child",
            name="spoken_name",
            field=models.CharField(
                blank=True,
                help_text=(
                    "Optional pronunciation spelling used only for generated spoken "
                    "menus. Leave blank to speak the child's name."
                ),
                max_length=200,
            ),
        ),
    ]
