# Generated by Django 5.2.15 on 2026-09-19 21:25

import directory.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def populate_codes(apps, schema_editor):
    Family = apps.get_model("directory", "Family")
    for family in Family.objects.using(schema_editor.connection.alias).all().iterator():
        family.invite_code = directory.models.new_family_invite_code()
        family.save(update_fields=["invite_code"])


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0015_remove_dialshortcut_dial_shortcut_has_exactly_one_target_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='child',
            name='color',
            field=models.CharField(choices=[('yellow', 'Yellow'), ('blue', 'Blue'), ('lavender', 'Lavender'), ('peach', 'Peach'), ('green', 'Green')], default='yellow', max_length=10),
        ),
        migrations.AddField(
            model_name='family',
            name='directory_listed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='family',
            name='invite_code',
            field=models.CharField(editable=False, max_length=32, null=True),
        ),
        migrations.RunPython(populate_codes, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='family', name='invite_code',
            field=models.CharField(default=directory.models.new_family_invite_code, editable=False, max_length=32, unique=True),
        ),
        migrations.AddField(
            model_name='family',
            name='setup_dismissed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='parent',
            name='directory_visible',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='parent',
            name='emergency_notice_dismissed',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='FamilyActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('description', models.CharField(max_length=500)),
                ('actor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('family', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity', to='directory.family')),
            ],
            options={
                'ordering': ['-created_at', '-pk'],
            },
        ),
    ]
