# Generated by Django 5.2.15 on 2026-09-19 21:41

import django.db.models.deletion
from django.db import migrations, models


def migrate_approved_pairs(apps, schema_editor):
    Relationship = apps.get_model("directory", "AllowedChildFamilyRelationship")
    ChildConnection = apps.get_model("directory", "ChildConnection")
    alias = schema_editor.connection.alias
    relationships = list(Relationship.objects.using(alias).filter(
        approved_by_child_family_guardian__isnull=False,
        approved_by_target_family_guardian__isnull=False,
    ).select_related("child"))
    for left in relationships:
        for right in relationships:
            if (left.child_id < right.child_id and left.child.family_id == right.target_family_id
                    and right.child.family_id == left.target_family_id):
                ChildConnection.objects.using(alias).get_or_create(
                    child_a_id=left.child_id, child_b_id=right.child_id,
                    defaults={"approved_by_a_id": left.approved_by_child_family_guardian_id,
                              "approved_by_b_id": right.approved_by_child_family_guardian_id})


    Invitation = apps.get_model("directory", "ConnectionInvitation")
    pending = Relationship.objects.using(alias).filter(
        approved_by_child_family_guardian__isnull=False,
        approved_by_target_family_guardian__isnull=True,
    ).select_related("child").order_by("pk")
    for relationship in pending:
        invitation, _ = Invitation.objects.using(alias).get_or_create(
            source_family_id=relationship.child.family_id,
            target_family_id=relationship.target_family_id,
            status="pending",
            defaults={"sent_by_id": relationship.approved_by_child_family_guardian_id,
                      "message": relationship.notes[:1000]},
        )
        invitation.source_children.add(relationship.child_id)


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0016_child_color_family_directory_listed_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChildConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('approved_by_a', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='child_connections_as_a', to='directory.parent')),
                ('approved_by_b', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='child_connections_as_b', to='directory.parent')),
                ('child_a', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='connections_as_a', to='directory.child')),
                ('child_b', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='connections_as_b', to='directory.child')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('child_a', 'child_b'), name='unique_child_connection'), models.CheckConstraint(condition=models.Q(('child_a__lt', models.F('child_b'))), name='ordered_child_connection')],
            },
        ),
        migrations.CreateModel(
            name='ConnectionInvitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('message', models.TextField(blank=True, max_length=1000)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('declined', 'Declined'), ('cancelled', 'Cancelled')], default='pending', max_length=12)),
                ('accepted_children', models.ManyToManyField(blank=True, related_name='accepted_connection_invitations', to='directory.child')),
                ('responded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='answered_connection_invitations', to='directory.parent')),
                ('sent_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sent_connection_invitations', to='directory.parent')),
                ('source_children', models.ManyToManyField(related_name='sent_connection_invitations', to='directory.child')),
                ('source_family', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_connection_invitations', to='directory.family')),
                ('target_family', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_connection_invitations', to='directory.family')),
            ],
            options={
                'ordering': ['-created_at', '-pk'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('status', 'pending')), fields=('source_family', 'target_family'), name='one_pending_invitation_per_family_direction')],
            },
        ),
        migrations.RunPython(migrate_approved_pairs, migrations.RunPython.noop),
    ]
