# Generated by Django 5.2.15 on 2026-09-19 21:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def select_primary_guardians(apps, schema_editor):
    Family = apps.get_model("directory", "Family")
    Parent = apps.get_model("directory", "Parent")
    alias = schema_editor.connection.alias
    for family in Family.objects.using(alias).all().iterator():
        guardians = Parent.objects.using(alias).filter(family=family, is_guardian=True).order_by("created_at", "pk")
        guardian = guardians.exclude(user_id=None).first() or guardians.first()
        if guardian:
            guardian.is_primary = True
            guardian.save(update_fields=["is_primary"])


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0017_childconnection_connectioninvitation'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GuardianInvitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('display_name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('token_digest', models.CharField(editable=False, max_length=64, unique=True)),
                ('expires_at', models.DateTimeField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('cancelled', 'Cancelled'), ('replaced', 'Replaced')], default='pending', max_length=12)),
            ],
            options={
                'ordering': ['-created_at', '-pk'],
            },
        ),
        migrations.AddField(
            model_name='parent',
            name='is_primary',
            field=models.BooleanField(default=False),
        ),
        migrations.AddConstraint(
            model_name='parent',
            constraint=models.UniqueConstraint(condition=models.Q(('is_primary', True)), fields=('family',), name='one_primary_guardian_per_family'),
        ),
        migrations.AddField(
            model_name='guardianinvitation',
            name='family',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guardian_invitations', to='directory.family'),
        ),
        migrations.AddField(
            model_name='guardianinvitation',
            name='invited_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='guardian_invitations_sent', to='directory.parent'),
        ),
        migrations.AddConstraint(
            model_name='guardianinvitation',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'pending')), fields=('family', 'email'), name='one_pending_guardian_invitation_per_email'),
        ),
        migrations.RunPython(select_primary_guardians, migrations.RunPython.noop),
    ]
