# Generated by Django 5.2.15 on 2026-09-21 03:03

import django.db.models.deletion
from django.db import migrations, models


def unify_parent_calls(apps, schema_editor):
    alias = schema_editor.connection.alias
    Parent = apps.get_model("directory", "Parent")
    Device = apps.get_model("directory", "Device")
    Shortcut = apps.get_model("directory", "DialShortcut")
    Activity = apps.get_model("directory", "FamilyActivity")
    with schema_editor.connection.cursor() as cursor:
        cursor.execute("SELECT pg_advisory_xact_lock(%s)", [0x46504F524348])
    used = set(Device.objects.using(alias).values_list("sip_extension", flat=True))
    for model in ("ExternalNumberExtension", "ChildLandline", "ConferenceGroup"):
        used.update(
            apps.get_model("directory", model)
            .objects.using(alias)
            .values_list("dial_extension", flat=True)
        )
    used.update({"100", "911"})
    available = (str(n) for n in range(1000, 10000) if str(n) not in used)
    for parent in Parent.objects.using(alias).order_by("pk"):
        devices = list(
            Device.objects.using(alias)
            .filter(assigned_parent_id=parent.pk)
            .order_by("-is_active", "pk")
        )
        extension = devices[0].sip_extension if devices else next(available, None)
        if (
            not extension
            or not extension.isascii()
            or not extension.isdigit()
            or len(extension) not in {3, 4}
            or extension in {"100", "911"}
        ):
            raise RuntimeError(
                "Parent calling upgrade requires a free valid extension. Review parent device extensions privately before retrying."
            )
        for model, field in (
            ("ExternalNumberExtension", "dial_extension"),
            ("ChildLandline", "dial_extension"),
            ("ConferenceGroup", "dial_extension"),
        ):
            destinations = (
                apps.get_model("directory", model)
                .objects.using(alias)
                .filter(**{field: extension})
            )
            if model == "ChildLandline":
                destinations = destinations.filter(is_active=True)
            if destinations.exists():
                raise RuntimeError(
                    "Parent calling upgrade found an extension collision. Resolve it privately before retrying."
                )
        if (
            Device.objects.using(alias)
            .filter(sip_extension=extension)
            .exclude(assigned_parent_id=parent.pk)
            .exists()
        ):
            raise RuntimeError(
                "Parent calling upgrade found an extension shared by different owners."
            )
        mobile_enabled = (
            bool(parent.phone)
            and Shortcut.objects.using(alias)
            .filter(
                parent_target_id=parent.pk,
                is_active=True,
                approved_by__family_id=parent.family_id,
                source_device__is_active=True,
                source_device__assigned_child__family_id=parent.family_id,
            )
            .exists()
        )
        has_sip = any(device.is_active for device in devices)
        destination = (
            ("both" if has_sip else "phone") if mobile_enabled else "frontporch"
        )
        Parent.objects.using(alias).filter(pk=parent.pk).update(
            dial_extension=extension, call_destination=destination
        )
        # Keep credentials and activation state; every device now shares its owner's number.
        Device.objects.using(alias).filter(assigned_parent_id=parent.pk).update(
            sip_extension=extension
        )
        Shortcut.objects.using(alias).filter(
            internal_target_device__assigned_parent_id=parent.pk
        ).update(
            parent_target_id=parent.pk,
            internal_target_device_id=None,
        )
        Activity.objects.using(alias).create(
            family_id=parent.family_id,
            actor_id=None,
            description=f"Unified calling for {parent.display_name} under one extension. Ring setting: {destination}.",
        )

    # Flush deferred FK checks before the following schema operations. Keep the
    # schema and data conversion in one transaction, including on populated DBs.
    with schema_editor.connection.cursor() as cursor:
        cursor.execute("SET CONSTRAINTS ALL IMMEDIATE")


def restore_legacy_targets(apps, schema_editor):
    # A schema rollback keeps calls usable. Restore a database backup to recover
    # exact former device numbers and per-shortcut transport choices.
    alias = schema_editor.connection.alias
    Parent = apps.get_model("directory", "Parent")
    Device = apps.get_model("directory", "Device")
    Shortcut = apps.get_model("directory", "DialShortcut")
    for parent in Parent.objects.using(alias).all():
        if parent.call_destination in {"disabled", "phone"}:
            Device.objects.using(alias).filter(assigned_parent_id=parent.pk).update(
                is_active=False
            )
        if parent.call_destination == "disabled":
            Shortcut.objects.using(alias).filter(parent_target_id=parent.pk).update(
                is_active=False
            )
        if parent.call_destination == "frontporch" or not parent.phone:
            device = (
                Device.objects.using(alias)
                .filter(assigned_parent_id=parent.pk)
                .order_by("-is_active", "pk")
                .first()
            )
            if device:
                Shortcut.objects.using(alias).filter(parent_target_id=parent.pk).update(
                    internal_target_device_id=device.pk,
                    parent_target_id=None,
                )

    with schema_editor.connection.cursor() as cursor:
        cursor.execute("SET CONSTRAINTS ALL IMMEDIATE")


class Migration(migrations.Migration):

    dependencies = [
        ("directory", "0020_guardian_accounts"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="dialshortcut",
            name="dial_shortcut_has_exactly_one_target",
        ),
        migrations.RenameField(
            model_name="dialshortcut",
            old_name="parent_phone_target",
            new_name="parent_target",
        ),
        migrations.AlterField(
            model_name="dialshortcut",
            name="parent_target",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="targeted_by_shortcuts",
                to="directory.parent",
            ),
        ),
        migrations.AddField(
            model_name="parent",
            name="call_destination",
            field=models.CharField(
                choices=[
                    ("frontporch", "FrontPorch phones"),
                    ("phone", "My phone number"),
                    ("both", "Both"),
                    ("disabled", "Do not ring me"),
                ],
                default="frontporch",
                max_length=12,
            ),
        ),
        migrations.AddField(
            model_name="parent",
            name="dial_extension",
            field=models.CharField(blank=True, max_length=4, unique=True, null=True),
        ),
        migrations.RunPython(unify_parent_calls, restore_legacy_targets),
        migrations.AlterField(
            model_name="parent",
            name="dial_extension",
            field=models.CharField(blank=True, max_length=4, unique=True),
        ),
        migrations.AddConstraint(
            model_name="dialshortcut",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("internal_target_device__isnull", False),
                        ("external_target_extension__isnull", True),
                        ("parent_target__isnull", True),
                        ("child_landline_target__isnull", True),
                        ("conference_group_target__isnull", True),
                    ),
                    models.Q(
                        ("internal_target_device__isnull", True),
                        ("external_target_extension__isnull", False),
                        ("parent_target__isnull", True),
                        ("child_landline_target__isnull", True),
                        ("conference_group_target__isnull", True),
                    ),
                    models.Q(
                        ("internal_target_device__isnull", True),
                        ("external_target_extension__isnull", True),
                        ("parent_target__isnull", False),
                        ("child_landline_target__isnull", True),
                        ("conference_group_target__isnull", True),
                    ),
                    models.Q(
                        ("internal_target_device__isnull", True),
                        ("external_target_extension__isnull", True),
                        ("parent_target__isnull", True),
                        ("child_landline_target__isnull", False),
                        ("conference_group_target__isnull", True),
                    ),
                    models.Q(
                        ("internal_target_device__isnull", True),
                        ("external_target_extension__isnull", True),
                        ("parent_target__isnull", True),
                        ("child_landline_target__isnull", True),
                        ("conference_group_target__isnull", False),
                    ),
                    _connector="OR",
                ),
                name="dial_shortcut_has_exactly_one_target",
            ),
        ),
    ]
