# Generated by Django 5.2.15 on 2026-09-25 01:10

from django.core.management.color import no_style
from django.db import migrations, models


ARCHIVE_TYPE = "retired_child_family_relationship_v1"


def guardian_snapshot(guardian):
    if guardian is None:
        return None
    return {
        "id": guardian.pk,
        "display_name": guardian.display_name,
        "user_id": guardian.user_id,
        "family_id": guardian.family_id,
        "family_name": guardian.family.name,
    }


def archive_relationships(apps, schema_editor):
    alias = schema_editor.connection.alias
    Relationship = apps.get_model("directory", "AllowedChildFamilyRelationship")
    Activity = apps.get_model("directory", "FamilyActivity")
    relationships = Relationship.objects.using(alias).select_related(
        "child__family",
        "target_family",
        "approved_by_child_family_guardian__family",
        "approved_by_target_family_guardian__family",
    )
    for relationship in relationships.order_by("pk").iterator():
        activity = Activity.objects.using(alias).create(
            family_id=relationship.child.family_id,
            actor_id=None,
            description=(
                f"Archived retired child-to-family approval #{relationship.pk} "
                "(history only)."
            ),
            details={
                "archive_type": ARCHIVE_TYPE,
                "id": relationship.pk,
                "created_at": relationship.created_at.isoformat(),
                "updated_at": relationship.updated_at.isoformat(),
                "child": {
                    "id": relationship.child_id,
                    "name": relationship.child.name,
                    "family_id": relationship.child.family_id,
                    "family_name": relationship.child.family.name,
                },
                "target_family": {
                    "id": relationship.target_family_id,
                    "name": relationship.target_family.name,
                },
                "approved_by_child_family_guardian": guardian_snapshot(
                    relationship.approved_by_child_family_guardian
                ),
                "approved_by_target_family_guardian": guardian_snapshot(
                    relationship.approved_by_target_family_guardian
                ),
                "notes": relationship.notes,
            },
        )
        # Keep historical events in their original place in the family's feed.
        Activity.objects.using(alias).filter(pk=activity.pk).update(
            created_at=relationship.created_at,
            updated_at=relationship.updated_at,
        )


def restore_relationships(apps, schema_editor):
    alias = schema_editor.connection.alias
    Relationship = apps.get_model("directory", "AllowedChildFamilyRelationship")
    Activity = apps.get_model("directory", "FamilyActivity")
    Child = apps.get_model("directory", "Child")
    Family = apps.get_model("directory", "Family")
    Parent = apps.get_model("directory", "Parent")
    archives = Activity.objects.using(alias).filter(details__archive_type=ARCHIVE_TYPE)
    for activity in archives.order_by("pk").iterator():
        snapshot = activity.details
        child_guardian = snapshot["approved_by_child_family_guardian"]
        target_guardian = snapshot["approved_by_target_family_guardian"]
        # Check before deferred foreign keys are installed by the schema editor,
        # so a missing identity cleanly rolls back the entire schema migration.
        references = [
            (Child, snapshot["child"]["id"]),
            (Family, snapshot["target_family"]["id"]),
        ]
        references.extend(
            (Parent, guardian["id"])
            for guardian in (child_guardian, target_guardian)
            if guardian is not None
        )
        if any(
            not model.objects.using(alias).filter(pk=pk).exists()
            for model, pk in references
        ):
            raise RuntimeError(
                "Cannot restore retired approval history: referenced people or "
                "families were removed. Restore a pre-upgrade database backup."
            )
        restored = Relationship.objects.using(alias).create(
            id=snapshot["id"],
            child_id=snapshot["child"]["id"],
            target_family_id=snapshot["target_family"]["id"],
            approved_by_child_family_guardian_id=(
                child_guardian["id"] if child_guardian else None
            ),
            approved_by_target_family_guardian_id=(
                target_guardian["id"] if target_guardian else None
            ),
            notes=snapshot["notes"],
        )
        Relationship.objects.using(alias).filter(pk=restored.pk).update(
            created_at=snapshot["created_at"], updated_at=snapshot["updated_at"]
        )
    for sql in schema_editor.connection.ops.sequence_reset_sql(no_style(), [Relationship]):
        schema_editor.execute(sql)
    archives.delete()


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0021_unified_parent_calling'),
    ]

    operations = [
        migrations.AddField(
            model_name="familyactivity",
            name="details",
            field=models.JSONField(blank=True, default=dict, editable=False),
        ),
        migrations.RunPython(archive_relationships, restore_relationships),
        migrations.DeleteModel(
            name='AllowedChildFamilyRelationship',
        ),
    ]
