# Generated by Django 5.2.15 on 2026-09-25 01:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0021_unified_parent_calling'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AllowedChildFamilyRelationship',
        ),
    ]
